### ISSUE TITLE
init.sh fails to init submodule libdevuansdk

### ISSUE THREAD

**Issue by not-a-bird** [parazyd/arm-sdk#3]
I followed the instructions to invoke the init.sh script after checking out the arm-sdk, but it fails with the following output:

    Cloning into '/home/not-a-bird/arm-sdk/lib/libdevuansdk'...
    fatal: Unable to look up git.parazyd.cf (port 9418) (Name or service not known)
    fatal: clone of 'git://git.parazyd.cf/libdevuansdk.git' into submodule path '/home/not-a-bird/arm-sdk/lib/libdevuansdk' failed
    Failed to clone 'lib/libdevuansdk'. Retry scheduled
    Cloning into '/home/not-a-bird/arm-sdk/lib/libdevuansdk'...
    fatal: Unable to look up git.parazyd.cf (port 9418) (Name or service not known)
    fatal: clone of 'git://git.parazyd.cf/libdevuansdk.git' into submodule path '/home/not-a-bird/arm-sdk/lib/libdevuansdk' failed
    Failed to clone 'lib/libdevuansdk' a second time, aborting

As a workaround, I can cd into lib and  `git clone git://parazyd.org/libdevuansdk.git` and then the init.sh runs happily.

Edit:  I don't see the same problem on my second system... the first one I did a git pull but maybe submodule config data doesn't get updated when you do that?  The second system doesn't have this problem.  I suspect this isn't an actual issue for recent checkouts.

**Comment by dderby** [comment]
I'm seeing the same problem when running a `git pull --rebase upstream master`.
